export const NAV_ITEMS = {
  Super_Admin: [
    { section: "Global" },
    { page: "/superadmin/dashboard", icon: "ti-layout-dashboard", label: "SA Dashboard" },
    { page: "/superadmin/monitoring", icon: "ti-activity", label: "Monitoring" },
    { page: "/superadmin/organisations", icon: "ti-building", label: "Organisations" },
    { page: "/superadmin/users", icon: "ti-users", label: "All Users" },
    { page: "/superadmin/audit-logs", icon: "ti-shield-check", label: "Global Audit Logs" },
  ],
  Admin: [
    { page: "/admin/dashboard", icon: "ti-layout-dashboard", label: "Dashboard" },
    { section: "Workflows" },
    { page: "/admin/approval-center", icon: "ti-check-square", label: "Approval Center" },
    { page: "/admin/purchase-approvals", icon: "ti-package-import", label: "Purchase Approvals" },
    { page: "/admin/revoke-approvals", icon: "ti-arrow-back-up", label: "Revoke Approvals" },
    { page: "/admin/lp-approvals", icon: "ti-file-invoice", label: "LP Approvals" },
    { section: "Reports" },
    { page: "/admin/attendance-management", icon: "ti-calendar-check", label: "Attendance Management" },
    { page: "/admin/inventory", icon: "ti-building-warehouse", label: "Store Inventory" },
    { page: "/admin/pl-report", icon: "ti-chart-bar", label: "P&L Report" },
    { section: "Settings" },
    { page: "/admin/skus", icon: "ti-tag", label: "SKU Registry" },
    { page: "/admin/users", icon: "ti-users", label: "User Registry" },
    { page: "/admin/audit-logs", icon: "ti-shield-check", label: "Audit Logs" },
  ],
  Store_Manager: [
    { section: "Operations" },
    { page: "/store/dashboard", icon: "ti-layout-dashboard", label: "Store Dashboard" },
    { page: "/store/inward", icon: "ti-package-import", label: "Purchase Inward" },
    { page: "/store/requests", icon: "ti-shopping-cart", label: "Stock Requests" },
    { page: "/store/return-requests", icon: "ti-arrow-back-up", label: "Return Requests" },
    { page: "/store/lp-requests", icon: "ti-file-invoice", label: "LP Requests" },
    { page: "/store/attendance", icon: "ti-calendar-plus", label: "My Attendance" },
    { section: "Reports & Settings" },
    { page: "/store/inventory", icon: "ti-clipboard-list", label: "Inventory Report" },
    { page: "/store/skus", icon: "ti-tag", label: "SKU Registry" },
  ],
  Team_Leader: [
    { section: "Team" },
    { page: "/tl/dashboard", icon: "ti-layout-dashboard", label: "Team Dashboard" },
    { page: "/tl/approvals", icon: "ti-check-square", label: "Validation Queue" },
    { page: "/tl/lp-requests", icon: "ti-file-invoice", label: "LP Requests" },
    { page: "/tl/attendance", icon: "ti-calendar-plus", label: "My Attendance" },
  ],
  Engineer: [
    { section: "My Work" },
    { page: "/engineer/dashboard", icon: "ti-layout-dashboard", label: "My Dashboard" },
    { page: "/engineer/productivity", icon: "ti-clipboard-check", label: "Productivity" },
    { section: "Inventory" },
    { page: "/engineer/stock", icon: "ti-package", label: "My Van Stock" },
  ],
};
